# Uncomment the next line to define a global platform for your project
 platform :ios, '15'

target 'iosApp' do
  pod 'shared', :path => '../shared'
  pod 'GoogleMaps', '9.2.0'
#  pod 'Google-Maps-iOS-Utils', '6.1.0'
end
